### ISSUE TITLE
Wrong tabindex for NTP server input field

### ISSUE THREAD

**Issue by cwickert** [yast/yast-caasp#24]
If you are using the *TAB* key to navigate on the overview screen, the focus jumps from "System Role" to *System Information* and skips *NTP Servers*. NTP is only the very last field to get the focus, which is quite annoying. Focus should follow match the graphical representation on the screen.

**Comment by cwickert** [comment]
Ping?!

**Comment by jreidinger** [comment]
I worry that it is related to fact that NTP field is dynamically added only for specific role. I worry that libyui does not allow to add tab index in middle or am I wrong? @shundhammer ?

**Comment by shundhammer** [comment]
@jreidinger: libyui adds widgets in the order as they appear in the UI term, right. I am not absolutely sure if that already defines the tab order for Qt (Qt itself, not libyui-qt), or if Qt tries to do any sorting by screen coordinates (probably not). For libyui-ncurses I am quite sure that it's the order in the UI term that matters.

Depending on the complexity of the UI term (how VBoxes and HBoxes are nested, also if there are any ReplacePoints where widgets are later replaced), this might or might not be desired. Just think of RadioBoxes and similar grouping widgets where it is expected (!) to get to the next widget in that group, no matter if there are other widgets at the sides of that group.

Also please consider that there are limits to the level of convenience that a high-level UI toolkit like the YaST libyui can offer. Being able to handle both a graphical and a text UI and having a simple API that the average application programmer can handle does come at a cost.

It might be possible to improve the grouping in the UI term for this, but since there is also yet another dimension of required flexibility with those dynamic roles, there are (even more) limits.

Also, you can simply use that widget's keyboard shortcut (Alt- ??).

**Comment by shundhammer** [comment]
Besides that, it is well known that that CaaSP configuration dialog is utterly overcrowded. Don't blame the UI toolkit for not providing maximum user convenience for this kind of UI "design". This dialog pushes the YaST UI engine to its limits - and beyond.

**Comment by lslezak** [comment]
JFYI that all-in-one dialog has been dropped in CaaSP-4.0. I think we can close this issue.
